# Generated by Django 5.1.3 on 2024-11-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60)),
                ('codigo_postal', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('persona_contacto', models.CharField(max_length=60)),
                ('NOCemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('minutos_uso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trafico_entrante', models.DecimalField(decimal_places=4, max_digits=6)),
                ('trafico_saliente', models.DecimalField(decimal_places=4, max_digits=6)),
                ('precio_por_numero', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
