# Generated by Django 5.1.3 on 2024-11-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='pais',
            field=models.CharField(default='Argentina', max_length=30),
            preserve_default=False,
        ),
    ]
